### PR TITLE
Script for uploading to postgres

### PR DESCRIPTION
**Pull request by JacobCoblentz**
Downloaded lobbying data by industry from opensecrets, cleaned it, uploaded to postgres, and returned a CSV of all pharma lobbying transactions.

### CODE REVIEW

**Comment by jenniferthompson** [comment]
@JacobCoblentz This is great!! One quick thing I noticed - is it possible to remove the trailing spaces in the year column? If not, I (or whoever) can do it pretty quickly in "regular" R after this gets merged, but figured it would be cleaner to do it in the same file if possible (I haven't used RPostgreSQL so don't know what it's capable of!).

**Comment by JacobCoblentz** [comment]
Yeah- uno momento.

**Comment by JacobCoblentz** [comment]
Done.

**Comment by JacobCoblentz** [comment]
@jenniferthompson done- will build the crosswalk for drug-->company tomorrow. Busy freaking out on twitter  rn

**Comment by jenniferthompson** [comment]
Awesome - thanks! (and, yes. I had to shut it off)

**Pull request merged**
