### PR TITLE
New README

### PR DESCRIPTION
**Pull request by mattgawarecki**
Goal here is to re-format our initial README to match the initial guidelines laid out by @bstarling. This is a first draft -- feedback encouraged!

NOTE: I recommend looking at the readme in this PR in Markdown format: https://github.com/mattgawarecki/drug-spending/blob/readme/README.md

### CODE REVIEW

**Comment by zachmueller** [comment]
I think it looks good! Some of the content you put together under your FAQ section might be well suited to move over to a D4D "shared" repo at some point. Very awesome to start documenting that kind of thing =) I'll let the other two read through it and provide their own feedback since I've fallen behind on the latest that's happening in this project lol.

**Comment by bstarling** [comment]
Nice! Might have to borrow some of your wording 👍

**Comment by jenniferthompson** [comment]
This is really fantastic, @mattgawarecki!

Might change one thing - based on my (limited) exposure to Jupyter, I think a better corollary would be [RMarkdown](http://rmarkdown.rstudio.com/) documents/[R Notebooks](http://rmarkdown.rstudio.com/r_notebooks.html) (using RStudio as an IDE makes it easy to do these, plus RStudio people wrote the RMarkdown package, so it gets fuzzy, but you don't have to have RStudio to create them).

Otherwise I think this is *awesome.*

**Comment by mattgawarecki** [comment]
@jenniferthompson I've betrayed my naivete of the R ecosystem! 😱 Oh well. :-) I did try to make corrections to the parts I thought you were referencing -- did that do the trick?

**Comment by jenniferthompson** [comment]
haha! I'm naive about much of this, trust me. :) Looks good - I was also thinking about the line "There are many ways to analyze the data..., ...Jupyter and RStudio."

**Comment by zachmueller** [comment]
Overall sounds like @mattgawarecki's edits are a big step in the right direction. Should we go ahead and merge this in then continue iterating on the bits and pieces as we hammer out the details?

**Comment by mattgawarecki** [comment]
I'll go ahead and merge -- looks like the big stuff passed muster and we've just got finer details to knock out. I actually have a couple other things to edit that I'll put into another PR today.

**Pull request merged**
